[package]
name = "realms_world"
version = "0.1.0"

[tool.dojo.world]
name = "Realms World"
description = "Realms World"
icon_uri = "file://assets/icon.png"
cover_uri = "file://assets/cover.png"
socials.x = "https://x.com/LootRealms"
socials.discord = "https://discord.gg/realmsworld"
socials.github = "https://github.com/BibliothecaDAO/RealmsWorld"
socials.telegram = "https://t.me/+HgJKXPwucOM4Njll"
website = "https://realms.world"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.0" }
token = { git = "https://github.com/dojoengine/origami", commit = "daa1646" }

[tool.dojo.env]
# Katana
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050"

[[target.dojo]]
build-external-contracts = [
    "token::components::security::initializable::initializable_model",
    "token::components::token::erc20::erc20_metadata::erc_20_metadata_model",
    "token::components::token::erc20::erc20_balance::erc_20_balance_model",
    "token::components::token::erc20::erc20_allowance::erc_20_allowance_model",
    "token::components::token::erc20::erc20_mintable::erc_20_mintable_model",
    "token::components::token::erc20::erc20_burnable::erc_20_burnable_model",
    "token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model",
]
